# Site settings
title: Recetario
email: ann_eav@hotmail.com
description: The plain text recipe database for hackers
baseurl: ""
language: "es"
lang_direction: "ltr"
color: "#007FFF"
twitter_username: ana_eav
github_username:  ValKiriann

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  es:
    components: "Componentes"
    ingredients: "Ingredientes"
    directions: "Instrucciones"
    category: "Categorías"
    nutritional_information: "Información nutricional"
    component_based: 'Esta es una receta<strong class="blue">compuesta</strong>.'
    search: "Buscar"
    blog: "Blog"
    subscribe: "Suscribirse"
  en:
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="blue">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
  de:
    components: "Komponenten"
    ingredients: "Zutaten"
    directions: "Zubereitung"
    category: "Kategorie"
    nutritional_information: "Nährwertangaben"
    component_based: 'Dieses Rezept besteht aus <strong class="blue">mehreren Komponenten</strong>.'
    search: "Suche"
    blog: "Blog"
    subscribe: "Abonnieren"